# -*- coding: utf-8 -*-
"""code12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrAHz4j42-KrCynYIfNFU9aSyNVhjpls
"""

name=input("enter the name")
print(len(name))

str="shifa$khan$"
print(str.count("$"))

light="green"

if(light=="red"):
  print("stop")
elif(light=="yellow"):
  print("look")
else:
  print("go")

age=24

if(age>=18):
  print("suitable for license")
else:
  print("not suitable for license")

marks=77

if(marks>=90):
  print("grade A")
elif(marks>=80):
  print("grade B")
elif(marks>=70):
  print("grade c")
else:
  print("grade d")

number=70
if(number%2==0):
  print("even")
else:
  print("odd")

a=6
b=8
c=3

if(a>b & a>c):
  print("A is greatest")
elif(b>a & b>c):
  print("B is greatest")
else:
  print("c is greatest")

number=77
if(number%7==0):
  print("multiple of 7")
else:
  print("multiple of 7")

